### ISSUE TITLE
MainGameDlg instance has no attribute 'onSystems'

### ISSUE THREAD

**Issue by Malxe** [OuterDeepSpace/OuterDeepSpace#14]
Issue happens when going from menu Planets | System List

Screenshot: http://i.imgur.com/DKnjBdf.jpg

**Comment by Ragora** [comment]
It looks like this code is to blame:

https://github.com/OuterDeepSpace/OuterDeepSpace/blob/master/libs/client/osci/dialog/MainGameDlg.py#L381

The main game dialog actually has no handlers for "onSystems", so unless its floating around somewhere, we're going to have to code it or remove it.

**Comment by Malxe** [comment]
Oh that sounds like fun.  I do recall this dialog used to work at one point.  But I can't say specifically when

**Comment by Ragora** [comment]
It does look like we want to use this dialog for it: https://github.com/OuterDeepSpace/OuterDeepSpace/blob/master/libs/client/osci/dialog/SystemOverviewDlg.py

Does that seem familiar at all?

**Comment by Ragora** [comment]
Fixed in PR #16
