### ISSUE TITLE
There should be a GUI method to specify a server

### ISSUE THREAD

**Issue by ghost** [OuterDeepSpace/OuterDeepSpace#31]
Pretty much what it says on the tin. Right now, the only way to tell the client what server you want to use is to manually edit osci.ini. Having at least a way to plug in a hostname and port in-game would be neat, and to take the idea further, a "favorite servers" screen might facilitate hopping between sessions for players with several communities.

**Comment by Malxe** [comment]
Feature added in pull request #34.
Closing issue.
