### ISSUE TITLE
Implement a Modern Database

### ISSUE THREAD

**Issue by Ragora** [OuterDeepSpace/OuterDeepSpace#6]
For the love of everything holy, bringing in a database that isn't metakit would be lovely for whenever this can get done. SQLAlchemy might be a good fit, unless there's something that operates much closer to the way metakit is running now to ease porting.

**Comment by atmafox** [comment]
This is a great idea, but metakit works for the time being and changing the DB system is a large enough task that I don't feel it is appropriate to be done on the legacy codebase.

**Comment by Ragora** [comment]
Considering that my problems were just the fact that the DB was literally empty, it should be okay as we can seem to run metakit on modern Python at least.
